### ISSUE TITLE
Error using Mamba to install Pygis

### ISSUE THREAD

**Issue by tariah7** [opengeos/pygis#6]
I got this error message while running `mamba install -c conda-forge pygis`

`(geo) C:\Users\victor>mamba install -c conda-forge pygis
Traceback (most recent call last):
  File "C:\Users\victor\miniconda3\envs\geo\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\victor\miniconda3\envs\geo\lib\site-packages\mamba\mamba.py", line 49, in <module>
    import libmambapy as api
  File "C:\Users\victor\miniconda3\envs\geo\lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Users\victor\miniconda3\envs\geo\lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
`
Please what could be the reason?

**Comment by giswqs** [comment]
This appears to be an issue with mamba rather than pygis. See https://github.com/mamba-org/mamba/issues/1728

**Comment by tariah7** [comment]
Thank you very much for the feedback
